version: '3.7'
services:
  application:
    image: ${APP_IMAGE}
    volumes:
      - ./src:/app
    ports:
      - 3000:80
    depends_on:
      - database
      - localstack
    environment:
      ACME_DIRECTORY: "https://acme-staging-v02.api.letsencrypt.org/directory"
      AWS_ACCESS_KEY_ID: access-key-id
      AWS_SECRET_ACCESS_KEY: access-key-secret
      AWS_REGION: eu-central-1
      AWS_S3_BUCKET_NAME: letsencrypt-bucket
      AWS_S3_ENDPOINT: http://localstack:4566
      AWS_S3_IGNORE_CONFIGURED_ENDPOINT: 1
      CORS_HOST: "*"
      DB_HOST: database
      DB_NAME: letsencrypt
      DB_PASSWORD: supersecurepassword
      DB_USER: root
      PASSWORD_PEPPER: 5cb55df11d72f511bc4d1d00ad22c5f3ddeea82e68cf57

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: letsencrypt
      POSTGRES_USER: root
      POSTGRES_PASSWORD: supersecurepassword

  localstack:
    image: localstack/localstack:latest
    environment:
      REGION: eu-central-1
      EDGE_PORT: 4566
      SERVICES: s3
    ports:
      - 4566:4566
    volumes:
      - ./.localstack:/etc/localstack/init/ready.d
