version: '3.7'
services:
  application:
    image: ${APP_IMAGE}
    volumes:
      - ./src:/app
    ports:
      - 3000:80
    depends_on:
      - database
    environment:
      AWS_ENDPOINT: http://localstack:4566
      AWS_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: access-key-id
      AWS_ACCESS_KEY_SECRET: access-key-secret
      AWS_S3_BUCKETNAME: letsencrypt-bucket
      DB_HOST: database
      DB_NAME: letsencrypt
      DB_USER: root
      DB_PASSWORD: supersecurepassword
      PASSWORD_PEPPER: 5cb55df11d72f511bc4d1d00ad22c5f3ddeea82e68cf57
      CORS_HOST: "*"

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: letsencrypt
      POSTGRES_USER: root
      POSTGRES_PASSWORD: supersecurepassword

  localstack:
    image: localstack/localstack:latest
    environment:
      REGION: eu-central-1
      EDGE_PORT: 4566
      SERVICES: s3
