# frozen_string_literal: true

AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Naming/ConstantName:
  Exclude:
    - "config/initializer/logger.rb"

Style/StringConcatenation:
  Exclude:
    - "config/initializer/logger.rb"

Lint/RedundantDirGlobSort:
  Exclude:
    - "config/api.rb"
    - "config/application.rb"
