# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.2.2"

gem "acme-client"
gem "aws-sdk-s3"
gem "dry-schema"
gem "pg"
gem "puma"
gem "rack-cors"
gem "roda"
gem "sequel"
gem "sequel_pg", require: "sequel"

# Gems for testing
gem "database_cleaner-sequel", require: false
gem "factory_bot"
gem "pry", require: false
gem "rack-test", require: false
gem "rspec", require: false
gem "rubocop", require: false
gem "simplecov", require: false
gem "webmock", require: false
