# This workflow will build and test container image

name: Build and test

on: pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v1
    - uses: docker/build-push-action@v2

    - name: Build and test
      run: make test
